#!/bin/bash
echo "netup!!">>/boot/log.txt

telegram()
{
   local VARIABLE=${1}
   curl -s -X POST https://blackbox.surfwijzer.nl/telegram.php -d text="netup: $VARIABLE" >/dev/null
}

telegram "netup"


