#!/bin/sh

#ETHTOOL=/sbin/ethtool

#test -x $ETHTOOL || exit 0



telegram()
{
   local VARIABLE=${1}
   curl -s -X POST https://blackbox.surfwijzer.nl/telegram.php -d text="networkup: $VARIABLE" >/dev/null
}


telegram "if-up.d/networkup"
